title: DesktopWords
author: cspablocortez
email: ""
description: >- # this means to ignore newlines until "baseurl:"
  A blog about people, writing, and technology.
baseurl: "" # the subpath of your site, e.g. /blog
domain: desktopwords
url: "https://desktopwords.com" 
github_username:  

theme: 
remote_theme: cspablocortez/arrow-jekyll-theme

plugins:
  - jekyll-remote-theme
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
